<?php


namespace xZeroMCPE\Zeroify\Team\Defaults;


use pocketmine\utils\TextFormat;
use xZeroMCPE\Zeroify\Configuration\MessageConfiguration;
use xZeroMCPE\Zeroify\Team\Team;
use xZeroMCPE\Zeroify\ZeroifyPlayer;

class SpectatorTeam extends Team
{

    public function init(ZeroifyPlayer $player)
    {
        parent::init($player); // TODO: Change the autogenerated stub

        $message = new MessageConfiguration(MessageConfiguration::format(
            "Death",
            TextFormat::YELLOW,
            "You died, you are now spectating..."
        ),
        "", "");
        $message->handle($player);
    }
}